language: elixir

sudo: false

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  include:
    - otp_release: 18.3
      elixir: 1.3
      script: mix test
    - otp_release: 19.3
      elixir: 1.3
      script: mix test
    - otp_release: 18.3
      elixir: 1.4
    - otp_release: 19.3
      elixir: 1.4

before_script:
#  - openssl s_client -connect hex.pm:443 -cipher 'DEFAULT:!ECDH'
  - mix deps.get --only test
  - nvm install 8.0 && nvm use 8.0
  - npm install -g elm

script:
  - npm install
  - npm run build
  - mix test
  - npm test

after_script:
  - cd $TRAVIS_BUILD_DIR
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
