language: elixir
elixir:
  - 1.5

dist: trusty

sudo: true

services:
  - postgresql

addons:
  postgresql: 9.5

env:
  - POSTGRES_PASSWORD=""

before_script:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
  - mix deps.get --only test
  - nvm install 8.0 && nvm use 8.0
  - npm install -g elm elm-test

script:
  - npm install
  - elm-package install -y
  - git clone https://github.com/obmarg/libsysconfcpus.git
  - cd libsysconfcpus
  - ./configure --prefix=/home/ubuntu/sysconfcpus;
  - sudo make install
  - cd ..
  - /home/ubuntu/sysconfcpus/bin/sysconfcpus -n 2 npm run build
  - mix ecto.create
  - mix ecto.migrate
  - mix test --trace

